TobeAppWeb/TobeAppWeb/Models/ReporteCovid.cs
using System;
using System.Collections.Generic;

namespace TobeAppWeb.Models
{
    public partial class ReporteCovid
    {
        public ReporteCovid()
        {
            NotificacionesaReporteCovid = new HashSet<NotificacionesaReporteCovid>();
        }

        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int? IdSedes { get; set; }
        public string Nombre { get; set; }
        public string NumerodeIdentificacion { get; set; }
        public DateTime? Fecha { get; set; }
        public string AreadeTrabajo { get; set; }
        public string Sintomas { get; set; }
        public string SintomasFamilia { get; set; }
        public string Rta6 { get; set; }
        public string Rta7 { get; set; }
        public string Rta8 { get; set; }
        public string Rta9 { get; set; }
        public string Estadodeanimo { get; set; }
        public string Enfermedades { get; set; }
        public string Iratrabajar { get; set; }
        public string Comentarios { get; set; }
        public int NumerodeSintomas { get; set; }
        public int Notificado { get; set; }
        public bool? NotificadoU { get; set; }

        public virtual Sedes IdSedesNavigation { get; set; }
        public virtual Usuarios IdUsuarioNavigation { get; set; }
        public virtual ICollection<NotificacionesaReporteCovid> NotificacionesaReporteCovid { get; set; }
    }
}

TobeAppWeb/TobeAppWeb/Controllers/Reporte_CovidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TobeAppWeb.Modelos;
using TobeAppWeb.Models;

namespace TobeAppWeb.Controllers
{
    [Authorize(Roles = "Admin")]
    public class Reporte_CovidController : Controller
    {
        private readonly AppTobeContext _context;

        public Reporte_CovidController(AppTobeContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> IndexEnviarNotifi()
        {
             int año = DateTime.Today.Year;
             int dia = DateTime.Today.Day;
             int mes = DateTime.Today.Month;
            var datosUsua = await _context.AspNetUsers.SingleOrDefaultAsync(s => s.UserName == User.Identity.Name);
            var appTobeContext = _context.ReporteCovid.Include(r => r.IdUsuarioNavigation).Include(r => r.IdSedesNavigation.IdEntidadNavigation).Where(s => s.IdSedesNavigation.IdEntidad == datosUsua.IdEntidad && s.Notificado == 0 && s.NumerodeSintomas >= 3);
            DateTime fecha = new DateTime(año,mes,dia);
            var model = new List<ReporteCovidModel>();

            foreach (var info in appTobeContext)
            {

                var ReporteCovidModel = new ReporteCovidModel
                {
                    IdUsuario = info.IdUsuario,
                    Nombredeusuario = info.IdUsuarioNavigation.Nombredeusuario,
                    IdReporteCovid = info.Id,
                    Sede = info.IdSedesNavigation.NombreSede,
                    EntidadNotifica = info.IdSedesNavigation.IdEntidadNavigation.Entidad,
                    FechadeReporte = (DateTime)info.Fecha,
                    FechaActualparaNotificar = fecha,
                    NumerodeSintomas = info.NumerodeSintomas,
                    IraTrabajar = true,
                    CitaTelemedicina = false,
                    EstaSeleccionado = false,

                };

                

                model.Add(ReporteCovidModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> IndexEnviarNotifi(List<ReporteCovidModel> model)
        {
            

            for (int i = 0; i < model.Count; i++)
            {
                int result = 0;

                if (model[i].EstaSeleccionado)
                {
                    string iratr = null;
                    string citate = null;
                    if (model[i].IraTrabajar)
                    {
                         iratr = "No";
                    }
                    else
                    {
                         iratr = "Ir";
                    }
                    if (model[i].CitaTelemedicina)
                    {
                        citate = "Si";
                    }
                    else
                    {
                        citate = "No";
                    }
                    NotificacionesaReporteCovid noti = new NotificacionesaReporteCovid
                    {
                        //IdUsuario = model[i].IdUsuario,
                        EntidadNotifica = model[i].EntidadNotifica,
                        IdReporteCovid = model[i].IdReporteCovid,
                        FechaNotifica = model[i].FechaActualparaNotificar,
                        IraTrabajar = iratr,
                        CitaTelemedicina = citate,

                    }; 
                    _context.NotificacionesaReporteCovid.Add(noti);
                    result =await _context.SaveChangesAsync();
                    var ReporteCovid = await _context.ReporteCovid.FindAsync(model[i].IdReporteCovid);
                    ReporteCovid.Notificado = 1;
                    _context.SaveChanges();
                }
                else
                {
                    continue;
                }

                if (result>0)
                {
                    if (i < model.Count - 1)
                    {
                        continue;
                    }
                    else
                    {
                        return RedirectToAction("IndexEnviarNotifi");
                    }
                }

            }
            return RedirectToAction("IndexEnviarNotifi");


        }

        // GET: ReporteCovids
        public async Task<IActionResult> Index()
        {
            var datosUsua = await _context.AspNetUsers.SingleOrDefaultAsync(s => s.UserName == User.Identity.Name);
            var appTobeContext = _context.ReporteCovid.Include(s => s.IdUsuarioNavigation).Include(s => s.IdSedesNavigation).Where(s => s.IdSedesNavigation.IdEntidad == datosUsua.IdEntidad && s.Notificado == 1);
            return View(await appTobeContext.ToListAsync());
        }

        public async Task<IActionResult> IndexSinNotifi()
        {
            var datosUsua = await _context.AspNetUsers.SingleOrDefaultAsync(s => s.UserName == User.Identity.Name);
            var appTobeContext = _context.ReporteCovid.Include(s => s.IdUsuarioNavigation).Include(s => s.IdSedesNavigation).Where(s => s.IdSedesNavigation.IdEntidad == datosUsua.IdEntidad && s.Notificado == 0);
            return View(await appTobeContext.ToListAsync());
        }

        // GET: ReporteCovids/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reporteCovid = await _context.ReporteCovid
                .Include(r => r.IdSedesNavigation)
                .Include(r => r.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reporteCovid == null)
            {
                return NotFound();
            }
            var datosUsua = await _context.AspNetUsers.SingleOrDefaultAsync(s => s.UserName == User.Identity.Name);
            if (reporteCovid.IdSedesNavigation.IdEntidad != datosUsua.IdEntidad)
            {
                return NotFound();
            }

            return View(reporteCovid);
        }

      
        // GET: ReporteCovids/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reporteCovid = await _context.ReporteCovid
                .Include(r => r.IdSedesNavigation)
                .Include(r => r.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reporteCovid == null)
            {
                return NotFound();
            }
            var datosUsua = await _context.AspNetUsers.SingleOrDefaultAsync(s => s.UserName == User.Identity.Name);
            if (reporteCovid.IdSedesNavigation.IdEntidad != datosUsua.IdEntidad)
            {
                return NotFound();
            }
            return View(reporteCovid);
        }

        // POST: ReporteCovids/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reporteCovid = await _context.ReporteCovid.FindAsync(id);
            _context.ReporteCovid.Remove(reporteCovid);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReporteCovidExists(int id)
        {
            return _context.ReporteCovid.Any(e => e.Id == id);
        }
    }
}

TobeAppWeb/TobeAppWeb/Views/Reporte_Covid/Delete.cshtml
@model TobeAppWeb.Models.ReporteCovid

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>
    <link rel="stylesheet" href="/css/Detalles.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>


<h2>Eliminar</h2>

<h3>¿Está seguro que quiere eliminar este reporte?</h3>
<hr />
<div id="conten">

    <div class="dl-horizontal">
        <h1>
            @Html.DisplayNameFor(model => model.Nombre)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Nombre)
        </label>
        <h1>
            Número de identificación
        </h1>
        <label>
            @Html.DisplayFor(model => model.NumerodeIdentificacion)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Fecha)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Fecha)
        </label>
        <h1>
            Área de trabajo
        </h1>
        <label>
            @Html.DisplayFor(model => model.AreadeTrabajo)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Sintomas)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Sintomas)
        </label>
        <h1>
            Sintomas en la familia
        </h1>
        <label>
            @Html.DisplayFor(model => model.SintomasFamilia)
        </label>
        <h1>
            Contacto estrecho con alguien que haya presentado síntomas
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta6)
        </label>
        <h1>
            Personas con las que convive, tuvo contacto estrecho con algún caso positivo para covid-19
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta7)
        </label>
        <h1>
            Caso positivo para covid-19 en la familia
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta8)
        </label>
        <h1>
            Utiliza transporte público
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta9)
        </label>
        <h1>
            Otras enfermedades
        </h1>
        <label>
            @Html.DisplayFor(model => model.Enfermedades)
        </label>
        <h1>
            Capacidad de ir a la oficina
        </h1>
        <label>
            @Html.DisplayFor(model => model.Iratrabajar)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Comentarios)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Comentarios)
        </label>
        <h1>
            Número de sintomas
        </h1>
        <label>
            @Html.DisplayFor(model => model.NumerodeSintomas)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Notificado)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Notificado)
        </label>
        <h1>
            Nombre de usuario
        </h1>
        <label>
            @Html.DisplayFor(model => model.IdUsuarioNavigation.Nombredeusuario)
        </label><br /><br />
    </div>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-default" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

TobeAppWeb/TobeAppWeb/Views/Reporte_Covid/Details.cshtml
@model TobeAppWeb.Models.ReporteCovid

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>
    <link rel="stylesheet" href="/css/Detalles.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>

<h2>DetallesReporte de covid</h2>
<hr />
<div id="conten">

    <div class="dl-horizontal">
        <h1>
            @Html.DisplayNameFor(model => model.Nombre)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Nombre)
        </label>
        <h1>
            Número de identificación
        </h1>
        <label>
            @Html.DisplayFor(model => model.NumerodeIdentificacion)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Fecha)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Fecha)
        </label>
        <h1>
            Área de trabajo
        </h1>
        <label>
            @Html.DisplayFor(model => model.AreadeTrabajo)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Sintomas)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Sintomas)
        </label>
        <h1>
            Sintomas en la familia
        </h1>
        <label>
            @Html.DisplayFor(model => model.SintomasFamilia)
        </label>
        <h1>
            Contacto estrecho con alguien que haya presentado síntomas
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta6)
        </label>
        <h1>
            Personas con las que convive, tuvo contacto estrecho con algún caso positivo para covid-19
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta7)
        </label>
        <h1>
            Caso positivo para covid-19 en la familia
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta8)
        </label>
        <h1>
            Utiliza transporte público
        </h1>
        <label>
            @Html.DisplayFor(model => model.Rta9)
        </label>
        <h1>
            Otras enfermedades
        </h1>
        <label>
            @Html.DisplayFor(model => model.Enfermedades)
        </label>
        <h1>
            Capacidad de ir a la oficina
        </h1>
        <label>
            @Html.DisplayFor(model => model.Iratrabajar)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Comentarios)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Comentarios)
        </label>
        <h1>
            Número de sintomas
        </h1>
        <label>
            @Html.DisplayFor(model => model.NumerodeSintomas)
        </label>
        <h1>
            @Html.DisplayNameFor(model => model.Notificado)
        </h1>
        <label>
            @Html.DisplayFor(model => model.Notificado)
        </label>
        <h1>
            Nombre de usuario
        </h1>
        <label>
            @Html.DisplayFor(model => model.IdUsuarioNavigation.Nombredeusuario)
        </label><br /><br />
    </div>
    <div>
         <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
         <a asp-action="Index">Volver</a>
    </div>
</div>

TobeAppWeb/TobeAppWeb/Views/Reporte_Covid/Index.cshtml
@model IEnumerable<TobeAppWeb.Models.ReporteCovid>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>
    <link rel="stylesheet" href="/css/tablas.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>

<h2>Reportes notificados</h2>


<table class="GeneratedTable">
    <thead>
        <tr>
            <th>
                Nombre sede
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                Número de identificación
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                Área de trabajo
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sintomas)
            </th>
            <th>
                Sintomas en la familia
            </th>
            <th>
                Contacto estrecho con alguien que haya presentado síntomas
            </th>
            <th>
                Personas con las que convive, tuvo contacto estrecho con algún caso positivo para covid-19
            </th>
            <th>
                Caso positivo para covid-19 en la familia
            </th>
            <th>
                Utiliza transporte público
            </th>
            <th>
                Estados de animo
            </th>
            <th>
                Otras enfermedades
            </th>
            <th>
                Capacidad de ir a la oficina
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comentarios)
            </th>
            <th>
                Número de sintomas
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notificado)
            </th>
            <th>
                Correo electrónico
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdSedesNavigation.NombreSede)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumerodeIdentificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AreadeTrabajo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sintomas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SintomasFamilia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rta6)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rta7)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rta8)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rta9)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estadodeanimo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enfermedades)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Iratrabajar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comentarios)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumerodeSintomas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notificado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsuarioNavigation.Nombredeusuario)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

TobeAppWeb/TobeAppWeb/Views/Reporte_Covid/IndexEnviarNotifi.cshtml
@model List<TobeAppWeb.Modelos.ReporteCovidModel>

@{
    ViewData["Title"] = "IndexPrueba";
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}


<head>
    <link rel="stylesheet" href="/css/tablas.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>

<h2>Enviar notificación</h2>
<label><input type="checkbox" id="iratrabajar" value="first_checkbox" checked="checked">No ir a la oficina</label>

<label><input type="checkbox" id="citateleme" value="first_checkbox" > Cita de Telemedicina</label>

<label><input type="checkbox" id="selectall" value="first_checkbox">Seleccionar todo</label>


<br>
<br>
<br>

<form asp-action="IndexEnviarNotifi" method="post">
    <table class="GeneratedTable">
        <thead>
            <tr><th>Usuario</th><th>Nombre de la sede</th><th>Fecha del reporte</th><th>Fecha actual</th><th>Numero de sintomas</th><th>No ir a la oficina</th><th>Cita de Telemedicina</th><th>Seleccionar </th></tr>
        </thead>
        
            @for (var i = 0; i < Model.Count; i++)
            {
            <tr>
                <th><label class="form-check-label" asp-for="@Model[i].EstaSeleccionado">@Model[i].Nombredeusuario</label><input type="hidden" asp-for="@Model[i].IdUsuario" /></th>
                <th><label class="form-check-label" asp-for="@Model[i].EstaSeleccionado">@Model[i].Sede</label><input type="hidden" asp-for="@Model[i].IdReporteCovid" /></th>
                <th><label class="form-check-label" asp-for="@Model[i].EstaSeleccionado">@Model[i].FechadeReporte</label><input type="hidden" asp-for="@Model[i].FechaActualparaNotificar" /></th>
                <th><label class="form-check-label" asp-for="@Model[i].EstaSeleccionado">@Model[i].FechaActualparaNotificar</label><input type="hidden" asp-for="@Model[i].EntidadNotifica" /></th>
                <th><label class="form-check-label" asp-for="@Model[i].EstaSeleccionado">@Model[i].NumerodeSintomas</label></th>
                <th><input asp-for="@Model[i].IraTrabajar" class="iratrabajar" /></th>
                <th><input asp-for="@Model[i].CitaTelemedicina" class="citateleme" /></th>
                <th><input asp-for="@Model[i].EstaSeleccionado" class="selectall" /></th>
                </tr>
                }
           
        </table>
    <br>
    <br>

    <div class="card-footer">
        <input type="submit" value="Actualizar" class="btn btn-primary" style="width:auto" />
            <a asp-action="IndexSinNotifi">Cancelar</a>
    </div>
</form>

<script>
      $(document).ready(function () {
        $('#selectall').on('click', function () {
          var checked_status = this.checked;

          $(".selectall").each(function () {
            this.checked = checked_status;
          });
        });
      });

    $(document).ready(function () {
        $('#citateleme').on('click', function () {
            var checked_status = this.checked;

            $(".citateleme").each(function () {
                this.checked = checked_status;
            });
        });
    });

    $(document).ready(function () {
        $('#iratrabajar').on('click', function () {
            var checked_status = this.checked;

            $(".iratrabajar").each(function () {
                this.checked = checked_status;
            });
        });
    });
</script>

TobeAppWeb/TobeAppWeb/Views/Reporte_Covid/IndexSinNotifi.cshtml
@model IEnumerable<TobeAppWeb.Models.ReporteCovid>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>
    <link rel="stylesheet" href="/css/tablas.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>


<h2>Notificaciones sin enviar</h2>

<p>
    <a asp-controller="Reporte_Covid" asp-action="IndexEnviarNotifi">Enviar notificaciones</a>
</p>

<hr />

<table class="GeneratedTable">
    <thead>
        <tr>
            <th>
                Nombre de la sede
            </th>
            <th>
                Nombre
            </th>
            <th>
                Número de identificación
            </th>
            <th>
                Fecha
            </th>
            <th>
                Área de trabajo
            </th>
            <th>
                Sintomas
            </th>
            <th>
                Sintomas en la familia
            </th>
            <th>
                Contacto estrecho con alguien que haya presentado síntomas
            </th>
            <th>
                Personas con las que convive, tuvo contacto estrecho con algún caso positivo para covid-19
            </th>
            <th>
                Caso positivo para covid-19 en la familia
            </th>
            <th>
                Utiliza transporte público
            </th>
            <th>
                Estados de animo
            </th>
            <th>
                Otras enfermedades
            </th>
            <th>
                Disposicion de ir a trabajar
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comentarios)
            </th>
            <th>
                Puntos sumados
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notificado)
            </th>

            <th>
                Correo electrónico
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdSedesNavigation.NombreSede)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumerodeIdentificacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AreadeTrabajo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sintomas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SintomasFamilia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rta6)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rta7)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rta8)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rta9)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estadodeanimo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Enfermedades)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Iratrabajar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comentarios)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumerodeSintomas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notificado)
                </td>>
                <td>
                    @Html.DisplayFor(modelItem => item.IdUsuarioNavigation.Nombredeusuario)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#selectall').on('click', function () {
            var checked_status = this.checked;

            $(".selectall").each(function () {
                this.checked = checked_status;
            });
        });
    });
</script>