TobeAppWeb/TobeAppWeb/Controllers/AdminisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using TobeAppWeb.Modelos;
using Microsoft.AspNetCore.Authorization;
using TobeAppWeb.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TobeAppWeb.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class AdminisController : Controller
    {
        //private readonly RoleManager<IdentityRole> roleManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> UsuarioManager;
        private readonly AppTobeContext _context;
        public AdminisController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> UsuarioManager, AppTobeContext context)
        {
            _context = context;
            this.roleManager = roleManager;
            this.UsuarioManager = UsuarioManager; 
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CrearRol model)
        {
            if (ModelState.IsValid)
            {
                // We just need to specify a unique role name to create a new role
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.NombreRol
                };

                // Saves the role in the underlying AspNetRoles table
                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        public ViewResult ListRoles() => View(roleManager.Roles);


        [HttpGet]
        public async Task<ActionResult> EditarRol (String id)
        {
            
            var rol = await roleManager.FindByIdAsync(id); 

            if (rol == null)
            {
                ViewBag.ErrorMessage = $"Rol con el id=  {id} no fue encontrado";
                return View("Error"); 
            }

            var model = new EditarRolViewmodel
            {
                Id = rol.Id,
                RolNombre = rol.Name
            };

            foreach (var usuario in UsuarioManager.Users)
            {
                if(await UsuarioManager.IsInRoleAsync(usuario, rol.Name))
                {
                    model.Usuarios.Add(usuario.UserName);
                }
            }

            return View(model); 

        }

        [HttpPost]
        public async Task<ActionResult> EditarRol(EditarRolViewmodel model)
        {
            var rol = await roleManager.FindByIdAsync(model.Id); 

            if (rol == null)
            {
                ViewBag.ErrorMessage = $"Rol con el id=  {model.Id} no fue encontrado";
                return View("Error");
            }
            else
            {
                rol.Name = model.RolNombre;
                var resultado = await roleManager.UpdateAsync(rol); 
                if (resultado.Succeeded)
                {
                    return RedirectToAction("ListRoles"); 
                }
                foreach (var error in resultado.Errors)
                {
                    ModelState.AddModelError("", error.Description); 
                }

                return View(model); 
            }
        }

        [HttpGet]
        public async Task<ActionResult> EditarUsuarioRol(String RolId)
        {
            ViewBag.roleId = RolId;

            var role = await roleManager.FindByIdAsync(RolId); 

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Rol con el id=  {RolId} no fue encontrado";
                return View("Error");
            }

            var model = new List<UsuarioRolmodelo>();

            foreach (var usuario in UsuarioManager.Users)
            {

                var usuarioRolmodelo = new UsuarioRolmodelo
                {
                    UsuarioID = usuario.Id,
                    UsuarioNombre = usuario.UserName,
                }; 

                if (await UsuarioManager.IsInRoleAsync(usuario, role.Name))
                {
                    usuarioRolmodelo.EstaSeleccionado = true; 
                }
                else
                {
                    usuarioRolmodelo.EstaSeleccionado = false;
                }

                model.Add(usuarioRolmodelo); 
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> EditarUsuarioRol(List<UsuarioRolmodelo> model, string RolId)
        {
            //var Datosu = RolId;
            var rol = await roleManager.FindByIdAsync(RolId);

              if(rol == null)
               {
                ViewBag.ErrorMessage = $"Rol con el id=  {RolId} no fue encontrado";
                 return View("Error");
              }

            for (int i= 0; i < model.Count; i++)
            {
                var user = await UsuarioManager.FindByIdAsync(model[i].UsuarioID);
                IdentityResult result = null; 

                if (model[i].EstaSeleccionado && !(await UsuarioManager.IsInRoleAsync(user, rol.Name)))
                {
                    result = await UsuarioManager.AddToRoleAsync(user, rol.Name); 
                }
                else if (!model[i].EstaSeleccionado && (await UsuarioManager.IsInRoleAsync(user, rol.Name)))
                {
                    result = await UsuarioManager.RemoveFromRoleAsync(user, rol.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < model.Count - 1)
                    {
                        continue; 
                    }
                    else
                    {
                        return RedirectToAction("EditarRol", new { Id = RolId });
                    }
                }

            }
            return RedirectToAction("EditarRol", new { Id = RolId });


        }

        [HttpGet]
        public IActionResult RegistroUsuarioAdmin()
        {
            ViewData["permiso"] = 2; 
            ViewData["IdEntidad"] = new SelectList(_context.Entidades, "Id", "Entidad");
            return View();
        }




    }
}

TobeAppWeb/TobeAppWeb/Views/Adminis/CreateRole.cshtml
@model TobeAppWeb.Modelos.CrearRol
@{
    ViewData["Title"] = "Crear nuevo rol";
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}
<head>
    <link rel="stylesheet" href="/css/Formularios.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>
    <h1>Crear nuevo roll</h1>
    <hr />

    <div id="conten">
        <form asp-action="CreateRole" method="post" class="mt-3">
            <div asp-validation-summary="All" class="text-danger">
            </div>
            <div class="form-group row">
                <label asp-for="NombreRol" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="NombreRol" type="text" class="form-control">
                    <span asp-validation-for="NombreRol" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" value="Crear roll" class="btn btn-primary" />
                    <a asp-action="ListRoles" class="btn btn-primary">
                        Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
    

  

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TobeAppWeb/TobeAppWeb/Views/Adminis/EditarRol.cshtml
@model TobeAppWeb.Modelos.EditarRolViewmodel

@{
    ViewData["Title"] = "EditarRol";

    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>
    <link rel="stylesheet" href="/css/tablas.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>

<h2>Editar rol</h2>

<hr />
<div class="row" id="conten">
    <div class="col-md-4">
        <form asp-action="EditarRol" method="post" class="mt-3">
            <div asp-validation-summary="All" class="text-danger">
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Nombre del rol</label>
                <div class="col-sm-10">
                    <input asp-for="RolNombre" type="text" class="form-control">
                    <span asp-validation-for="RolNombre" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" value="Editar" class="btn btn-primary" />
                    <a asp-action="ListRoles" class="btn btn-primary" style="width:auto">Cancelar</a>
                </div>
            </div>


            <div class="card">
                <div class="card-header">
                    <h2>Usuarios en este rol</h2>
                </div>
                <div class="card-body">

                    @if (Model.Usuarios.Any())
                    {
                        for (int i = 0; i < Model.Usuarios.Count; i++)
                        {
                            <h5 class="card-title">@Model.Usuarios[i]</h5>
                        }

                    }
                    else
                    {

                        <h5 class="card-title">Ninguno por ahora</h5>
                    }
                </div>

                <div class="card-footer">
                    <a asp-controller="Adminis" asp-action="EditarUsuarioRol" asp-route-RolId="@Model.Id"
                       class="btn btn-primary" style="width:auto">Crear o eliminar usuario</a>
                </div>

            </div>
        </form>
    </div>
</div>

TobeAppWeb/TobeAppWeb/Views/Adminis/EditarUsuarioRol.cshtml
@model List<TobeAppWeb.Modelos.UsuarioRolmodelo>

@{
    var roleId = ViewBag.roleId; 
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>


    <link rel="stylesheet" href="/css/Formularios.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>


<h2>Agregar o borrar usuarios de este rol</h2>
<hr />
<div id="conten">
    <form asp-action="EditarUsuarioRol" asp-route-RolId="@roleId" method="post" >

        <div class="card">
            <div class="card-header">

            </div>
            <div class="card-body">
                @{for (int i = 0; i < Model.Count; i++)
                    {
                        <div class="form-check m-1"></div>
                        <input type="hidden" asp-for="@Model[i].UsuarioID" />
                        <input type="hidden" asp-for="@Model[i].UsuarioNombre" />
                        <input asp-for="@Model[i].EstaSeleccionado" class="form-check-input" />
                        <label class="form-check-label" asp-for="@Model[i].EstaSeleccionado">
                            @Model[i].UsuarioNombre
                        </label>
                    }

                }
            </div>

            <div class="card-footer">
                <input type="submit" value="Actualizar" class="btn btn-primary" style="width:auto" />
                <a asp-action="EditarRol" asp-route-id="@roleId" class="btn btn-primary" style="width:auto">
                    Cancelar
                </a>
            </div>

        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TobeAppWeb/TobeAppWeb/Views/Adminis/ListRoles.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<IdentityRole>

@{
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>
    <link rel="stylesheet" href="/css/tablas.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>

<h1 class="bg-info text-white">Todos los roles</h1>

<a asp-action="CreateRole" class="btn btn-secondary">Crear un roll</a><br /><br />

<table class="GeneratedTable">
    <thead><tr><th>Nombre</th><th>Editar</th></tr></thead>
    @foreach (var role in Model)
    {
        <tr>
            
            <td>@role.Name</td>
            <td>
                <form asp-action="Delete" asp-route-id="@role.Id" method="post">
                   

                    <a asp-controller="Adminis" asp-action="EditarRol"
                       asp-route-id="@role.Id" class="btn btn-primary">
                        Editar
                    </a>
                </form>
            </td>
        </tr>
    }
</table>

TobeAppWeb/TobeAppWeb/Views/Adminis/RegistroUsuarioAdmin.cshtml
@model TobeAppWeb.Modelos.RegistroUsuariosAdmin; 
@{
    ViewData["Title"] = "RegistroUsuarioAdmin";
    Layout = "~/Views/Shared/_LayoutTobe.cshtml";
}

<head>
    <link rel="stylesheet" href="/css/Formularios.css" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Supe_Administrador</title>

</head>

<h2>Registro usuarios administradores</h2>

<div class="row" id="conten">
    <div class="col-md-12">
        <form method="post"></form>
        <div asp-validation-summary="All" class="text-danger">
            <div class="form-group">
                <label asp-for="correo"></label>
                <input asp-for="correo" class="form-control" />
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="password"></label>
                <input asp-for="password" class="form-control" value="ViewBag.permiso"/>
                <span asp-validation-for="password" class="text-danger" ></span>
            </div>

            <div class="form-group">
                <label asp-for="passwordValidar"></label>
                <input asp-for="passwordValidar" class="form-control" />
                <span asp-validation-for="passwordValidar" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Permiso"></label>
                <input asp-for="Permiso" class="form-control" />
                <span asp-validation-for="Permiso" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IdEntidad" class="control-label"></label>
                <select asp-for="IdEntidad" class="form-control" asp-items="ViewBag.IdEntidad"></select>
                <span asp-validation-for="IdEntidad" class="text-danger"></span>
            </div>

        </div>


    </div>


</div>